### ISSUE TITLE
Octoprint settings?

### ISSUE THREAD

**Issue by Googliola** [macdylan/sm2uploader#4]
What are the right settings to use the simulated octoprint?
Without IP, the upload button is not displayed
With correct IP, the upload works, but PS throws an error not being able to upload (connection test fails too, that is to be expected)
What settings would you recommend?
![image](https://user-images.githubusercontent.com/505490/233831770-c6ddbf12-79ea-4ac0-967a-44f2058bfe9f.png)
![image](https://user-images.githubusercontent.com/505490/233832029-9c7520a0-8d89-4123-b2ad-e703440d640b.png)

**Comment by macdylan** [comment]
If IP:Port is correct, opening it in the browser will display a 404 instead of any other error. Please make sure the port number is correct.

**Comment by apphead** [comment]
Ah, OK. port 8888 seems to be correct default.
Now, "RESOLVING ADDRESS" pops up and stays there forever. I prefer the "error" edition  ;-)
![image](https://user-images.githubusercontent.com/505490/233922542-7f7ac724-331c-46b0-bd1f-8c9550f57e8f.png)

**Comment by macdylan** [comment]
Please try this:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/331506/233923280-e05ab4a3-3240-4e91-adff-275501e34020.png">
<img width="587" alt="image" src="https://user-images.githubusercontent.com/331506/233923437-e73647d3-9fa5-4f72-873e-81fbb5ed0d5a.png">

**Comment by macdylan** [comment]
If you are running sm2up on another computer/nas/octopi, please make sure that the firewall is not blocking that port.

prusaslicer/s3d/ideamaker via OctoPrint protocol -> sm2up Dummy-OctoPrint-Service -> Snapmaker Printer via SM Protocols

That is how it works.
